#!/usr/bin/env bash
# sdlc-deep-reason-audit.sh — periodic post-hoc deep-reasoning audit
#
# Fired on a 7-day cooldown via orders/sdlc-deep-reason-audit.toml. For each
# active non-HQ rig, generates a fresh-context Opus deep-reasoning prompt
# against the last N patch tags' commits + diffs, writes the prompt to
# reviews/deep-reason-audit-<date>.md at the rig root, and notifies the
# operator via sdlc-notify.sh.
#
# Why a generated prompt instead of an automated `claude --print` invocation:
# v1 ships the simpler shape — prompt-as-artifact, operator dispatches the
# Claude Code session manually. The pack's experience shows that fresh-
# context Opus subagents reading the audit prompt + commits produce the
# right shape of findings; automating the dispatch is a follow-on (would
# require either a headless claude invocation or a dedicated auditor pool).
#
# Window selection: takes the last N tags since the most-recent-audited
# tag (bookmarked in .gc/deep-reason-audit-state.json). N defaults to 5
# via SDLC_DEEP_REASON_AUDIT_TAGS.
#
# Feature gate: SDLC_DEEP_REASON_AUDIT_ENABLED (default "false"). Defaults
# OFF because this order spawns external state — a prompt file + a
# notification per fire — and the operator should opt in explicitly after
# deciding to adopt the scheduled-audit pattern. (Other orders in the pack
# vary on default — zombie-reconciler and exhausted-bead-retry default OFF,
# rebase-watcher and stale-pr-sweeper default ON. There's no uniform
# convention; the per-order risk shapes the choice.)
#
# Idempotent against re-fires: writes its progress bookmark BEFORE
# notifying. A duplicate fire that finds the bookmark already at the
# latest tag does nothing.

set -uo pipefail

if [ "${SDLC_DEEP_REASON_AUDIT_ENABLED:-false}" != "true" ]; then
    exit 0
fi

# Resolve the city root via the shared resolver — gascity retired
# GC_CITY_ROOT from the order-exec env (issue #204); it now emits GC_CITY.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CITY_ROOT=$(bash "$SCRIPT_DIR/lib/sdlc-find-city-root.sh" 2>/dev/null) || CITY_ROOT=""
if [ -z "$CITY_ROOT" ] || [ ! -d "$CITY_ROOT" ]; then
    echo "deep-reason-audit: cannot resolve city root (GC_CITY_ROOT='${GC_CITY_ROOT:-}' GC_CITY='${GC_CITY:-}' PWD='$PWD'); cannot enumerate rigs" >&2
    exit 0
fi

if [ -z "${PACK_DIR:-}" ]; then
    PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
fi

NOTIFY="$PACK_DIR/assets/scripts/sdlc-notify.sh"
RIG_LISTER="$SCRIPT_DIR/lib/sdlc-list-rigs.sh"

if [ ! -x "$RIG_LISTER" ]; then
    echo "deep-reason-audit: rig-lister not executable at $RIG_LISTER" >&2
    exit 0
fi

TAGS_WINDOW="${SDLC_DEEP_REASON_AUDIT_TAGS:-5}"

# Per-rig: generate audit prompt against the last N tags / K days.
audit_rig() {
    local rig="$1"
    local rig_root="$2"

    if [ ! -d "$rig_root/.git" ]; then
        echo "deep-reason-audit: $rig has no .git dir; skipping" >&2
        return
    fi

    local state_file="$rig_root/.gc/deep-reason-audit-state.json"
    local last_audited_tag=""
    if [ -f "$state_file" ]; then
        last_audited_tag=$(jq -r '.last_audited_tag // ""' "$state_file" 2>/dev/null || echo "")
    fi

    # Build the window of tags. Take the last TAGS_WINDOW tags by version-name
    # order (newest version first). Using -v:refname is deterministic against
    # tags created in quick succession (same creator-date) — git's creatordate
    # sort is unstable on tied dates.
    local tags
    tags=$(cd "$rig_root" && git tag --sort=-v:refname | head -n "$TAGS_WINDOW")
    if [ -z "$tags" ]; then
        echo "deep-reason-audit: $rig has no tags; skipping" >&2
        return
    fi

    local latest_tag
    latest_tag=$(echo "$tags" | head -n 1)

    # Skip if the most-recent tag matches the last audited tag.
    if [ "$latest_tag" = "$last_audited_tag" ]; then
        return
    fi

    # Compute commit range: from oldest-tag-in-window to HEAD.
    local oldest_tag
    oldest_tag=$(echo "$tags" | tail -n 1)
    local commit_range="${oldest_tag}..HEAD"

    # Generate the audit prompt.
    local date_stamp
    date_stamp=$(date -u +%Y-%m-%d)
    local prompt_path="$rig_root/reviews/deep-reason-audit-${date_stamp}.md"
    mkdir -p "$(dirname "$prompt_path")"

    {
        echo "# Deep-reasoning audit prompt — $rig — $date_stamp"
        echo ""
        echo "Generated by orders/sdlc-deep-reason-audit.toml (cooldown order)."
        echo "Window: \`${commit_range}\` (last ${TAGS_WINDOW} tags from ${oldest_tag} forward)."
        echo ""
        echo "## How to dispatch"
        echo ""
        echo "1. Open Claude Code in this rig's directory."
        echo "2. Paste the prompt below."
        echo "3. The fresh-context Opus subagent will return a structured findings report."
        echo "4. Apply in-session corrections + file follow-on issues per the established pattern (see v2.29.6 + v2.29.10 README entries for shape)."
        echo ""
        echo "## Prompt"
        echo ""
        echo "\`\`\`"
        echo "You are evaluating the last ${TAGS_WINDOW} patch tags of the $rig rig"
        echo "against the pack's own software-engineering discipline rules at"
        echo "\$RIG_ROOT/.claude/rules/. Look for cleanup, consolidation, and"
        echo "modularity-for-reuse opportunities the implementer missed."
        echo ""
        echo "# Working environment"
        echo ""
        echo "- Repo: $rig_root"
        echo "- Tags in window: $(echo "$tags" | tr '\n' ' ')"
        echo "- Commit range: $commit_range"
        echo "- Discipline rules dir: $rig_root/.claude/rules/"
        echo ""
        echo "# Steps"
        echo ""
        echo "1. Read each tag's commit and diff via \`git show <tag>\`."
        echo "2. Read the pack's discipline rules under \`.claude/rules/\`."
        echo "3. For each commit, evaluate against the rules: Rule of Three, xUnit Test Spy"
        echo "   vocabulary, Tell-Don't-Ask, Two Hats, modularity boundaries."
        echo "4. Look for: missed consolidations, incomplete consolidations, modularity smells,"
        echo "   tech-debt-as-prose-not-issues, scope-narrowing claims, vocabulary drift,"
        echo "   aspirational test assertions."
        echo "5. Cross-check claims in each commit body / README narrative against the actual"
        echo "   diff content."
        echo ""
        echo "# Output spec"
        echo ""
        echo "Per-tag verdict (PASS / PASS-WITH-CAVEATS / NEEDS-REWORK) with 1-3 specific findings,"
        echo "cross-cutting findings spanning multiple tags, follow-on issues to file, in-session"
        echo "corrections to apply before next tag. 1500-2200 words. Same shape as v2.29.6 +"
        echo "v2.29.10 corrections cycles produced."
        echo ""
        echo "# Discipline"
        echo ""
        echo "- Verify every cited identifier — file paths, function names, commit SHAs."
        echo "- If a finding's root cause is upstream (spec under-scoping, audit gap), say so;"
        echo "  don't pretend a single-commit fix closes it."
        echo "- Operator writing register: senior IC, em dashes with spaces for parentheticals,"
        echo "  no tone markers, no hype words, sentence-case headings, US English, serial comma."
        echo "\`\`\`"
        echo ""
        echo "## Window details"
        echo ""
        echo "Tags in window (newest first):"
        echo ""
        echo "$tags" | sed 's/^/- /'
        echo ""
        echo "Last audited tag (from state bookmark): \`${last_audited_tag:-none}\`"
        echo ""
    } > "$prompt_path"

    # Bookmark the latest tag BEFORE notifying — idempotent against re-fires.
    mkdir -p "$rig_root/.gc"
    cat > "$state_file" <<EOF
{
  "last_audited_tag": "$latest_tag",
  "last_audit_date": "$date_stamp",
  "last_prompt_path": "$prompt_path"
}
EOF

    # Notify the operator.
    if [ -x "$NOTIFY" ]; then
        "$NOTIFY" --subject "deep-reason audit ready: $rig (${commit_range})" <<NOTIFY_EOF
Audit prompt generated for rig: $rig

Window: ${commit_range}
Tags in window:
$tags

Prompt file: $prompt_path

To dispatch: open Claude Code in $rig_root, paste the prompt section from
the file above, and review the findings report the agent returns.
NOTIFY_EOF
    fi
}

while IFS=$'\t' read -r rig_name rig_path; do
    [ -z "$rig_name" ] && continue
    audit_rig "$rig_name" "$rig_path"
done < <(bash "$RIG_LISTER" "$CITY_ROOT")
